export { ProfileHead } from './profileHead/ProfileHead'
export { Header } from './header/Header'
export { SideBar } from './sideBar/SideBar'
export { UserTabsNavigation } from './userTabsNavigation/UserTabsNavigation'
export { UserUploadedPhotosTab } from '@/entities/userUploadedPhotosTab/UserUploadedPhotosTab'